services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    pythonVersion: 3.11.9
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: BLOGGER_BLOG_ID_1
        sync: false
      - key: BLOGGER_API_KEY_1
        sync: false
      - key: BLOGGER_BLOG_ID_2
        sync: false
      - key: BLOGGER_API_KEY_2
        sync: false
      - key: REQUEST_NOTIFICATION_CHANNEL
        sync: false