services:
  - type: web
    name: movie-bot-web
    env: python
    plan: free
    region: singapore
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: "8080"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true